package com.sakhatech.util;

import java.util.Date;

import org.springframework.web.multipart.MultipartFile;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.sakhatech.dto.UserProfileDto;

/**
 * The utility class to generate a PDF
 * 
 * @author Naveen
 * @createdDate 7-Jun-2017
 * @modifiedDate 13-Jun-2017
 */
public class UserPDFGenUtility {
	
	private UserProfileDto userDetails;
	private Document document;
	
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    private static Font smallFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);
	
	public UserPDFGenUtility(UserProfileDto userDetails, Document document) {
		this.userDetails = userDetails;
		this.document = document;
	}
	
	private void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
	
	public void addFileDetails(){
		document.addTitle("User Profile Details");
		document.addSubject("Th document contains the user details");
		document.addKeywords("User , profile");
		document.addAuthor("Naveen Heroorkar");
		document.addCreator("sh.naveen16@gmail.com");
		document.addCreationDate();
	}

	public void addTitlePage() throws Exception {
		Paragraph pTitle = new Paragraph();
		pTitle.add(new Paragraph("The User Profile", catFont));
		
		pTitle.add(new Paragraph("The profile has been generated by using the java program" , redFont));
		
		pTitle.add(new Paragraph(
                "Report generated by: " + userDetails.getName() + ", " + new Date(), smallFont));
		
		document.add(pTitle);
		
		document.newPage();
		
	}
	
	public void addUserProfile() throws Exception {
		Paragraph pUserProfile = new Paragraph();
		
		pUserProfile.add(new Paragraph("Name : " +userDetails.getName()));
		pUserProfile.add(new Paragraph("Email : "+userDetails.getEmail()));
		pUserProfile.add(new Paragraph("Mobile : "+userDetails.getMobile()));	
		
		MultipartFile userImg = EncodeDecodeMultipartFile.decryptMultiPartFile(
				userDetails.getPhotoEncodedBase64(), userDetails.getName(), "", userDetails.getEmail());
		
		Image img = Image.getInstance(userImg.getBytes());
		Paragraph pUserImg = new Paragraph();
		pUserImg.add(img);
		pUserProfile.add(pUserImg);
		
		document.add(pUserProfile);
	}

	public Document getDocument() throws Exception {
		if(document == null)
			throw new Exception("Document is Empty");
		else
			return document;
	}

}
